--
-- $Header: script_practico_BASES_DE_DATOS_2008_05_21.sql
--
--   Este script implementa el modelo de datos mostrado en el archivo: 2008-05-21-PRACTICO_BASE_DE_DATOS.pdf
--


set termout on
prompt Construyendo las tablas del modelo de datos.  Por favor espere.
set termout off
set feedback off


ALTER SESSION SET NLS_LANGUAGE = AMERICAN;
ALTER SESSION SET NLS_TERRITORY = AMERICA;
alter session set nls_date_format = 'DD-MON-YY';


DROP TABLE EXAMENES CASCADE CONSTRAINTS;
DROP TABLE COMISIONES CASCADE CONSTRAINTS;
DROP TABLE MATERIAS CASCADE CONSTRAINTS;
DROP TABLE ALUMNOS CASCADE CONSTRAINTS;
DROP TABLE CARRERAS CASCADE CONSTRAINTS;
DROP TABLE PROFESORES CASCADE CONSTRAINTS;
DROP TABLE CIUDADES CASCADE CONSTRAINTS;
DROP TABLE PROVINCIAS CASCADE CONSTRAINTS;
DROP TABLE PAISES CASCADE CONSTRAINTS;


CREATE TABLE PAISES
( COD_PAIS			NUMBER(6),
  NOMBRE			VARCHAR2(64)	CONSTRAINT NOMBRE_PAIS_OBLIGATORIO			NOT NULL);

CREATE TABLE PROVINCIAS
( COD_PROVINCIA			NUMBER(9),
  NOMBRE			VARCHAR2(64)	CONSTRAINT NOMBRE_PROVINCIA_OBLIGATORIO			NOT NULL),
  COD_PAIS			NUMBER(6)	CONSTRAINT COD_PAIS_PROVINCIA_OBLIGATORIO		NOT NULL);

CREATE TABLE CIUDADES
( COD_CIUDAD			NUMBER(12),
  NOMBRE			VARCHAR2(64)	CONSTRAINT NOMBRE_CIUDAD_OBLIGATORIO			NOT NULL,
  COD_PROVINCIA			NUMBER(9)	CONSTRAINT COD_PROVINCIA_CIUDAD_OBLIGATORIO		NOT NULL,
  COD_PAIS			NUMBER(6)	CONSTRAINT COD_PAIS_CIUDAD_OBLIGATORIO			NOT NULL);

CREATE TABLE PROFESORES
( NRO_LEGAJO_PROFESOR		NUMBER(6),
  NRO_DOCUMENTO			NUMBER(9)	CONSTRAINT NRO_DOCUMENTO_PROFESOR_OBLIGATORIO		NOT NULL,
  APELLIDO			VARCHAR2(40)	CONSTRAINT APELLIDO_PROFESOR_OBLIGATORIO		NOT NULL,
  NOMBRE			VARCHAR2(40)	CONSTRAINT NOMBRE_PROFESOR_OBLIGATORIO			NOT NULL,
  LUGAR_NACIMIENTO		VARCHAR2(64)	CONSTRAINT LUGAR_NACIMIENTO_PROFESOR_OBLIGATORIO	NOT NULL,
  FECHA_NACIMIENTO		DATE		CONSTRAINT FECHA_NACIMIENTO_PROFESOR_OBLIGATORIO	NOT NULL,
  DOMICILIO			VARCHAR2(64)	CONSTRAINT DOMICILIO_PROFESOR_OBLIGATORIO		NOT NULL,
  TELEFONO			VARCHAR2(24)	CONSTRAINT TELEFONO_PROFESOR_OBLIGATORIO		NOT NULL,
  CORREO_ELECTRONICO		VARCHAR2(128)	CONSTRAINT CORREO_ELECTRONICO_PROFESOR_OBLIGATORIO	NOT NULL,
  COD_CIUDAD			NUMBER(12)	CONSTRAINT COD_CIUDAD_PROFESOR_OBLIGATORIO		NOT NULL,
  COD_PROVINCIA			NUMBER(9)	CONSTRAINT COD_PROVINCIA_PROFESOR_OBLIGATORIO		NOT NULL,
  COD_PAIS			NUMBER(6)	CONSTRAINT COD_PAIS_PROFESOR_OBLIGATORIO		NOT NULL,
  FECHA_INGRESO			DATE		CONSTRAINT FECHA_INGRESO_PROFESOR_OBLIGATORIO		NOT NULL);

CREATE TABLE CARRERAS
( COD_CARRERA			NUMBER(3),
  NOMBRE			VARCHAR2(64)	CONSTRAINT NOMBRE_CARRERA_OBLIGATORIO			NOT NULL,
  DURACION_ESTIMADA_ANIOS	NUMBER(2)	CONSTRAINT DURACION_ESTIMADA_ANIOS_CARRERA_OBLIGATORIO	NOT NULL);

CREATE TABLE ALUMNOS
( NRO_LEGAJO_ALUMNO		NUMBER(6),
  COD_CARRERA			NUMBER(3)	CONSTRAINT COD_CARRERA_ALUMNO_OBLIGATORIO		NOT NULL ,
  NRO_DOCUMENTO			NUMBER(9)	CONSTRAINT NRO_DOCUMENTO_ALUMNO_OBLIGATORIO		NOT NULL,
  APELLIDO			VARCHAR2(40)	CONSTRAINT APELLIDO_ALUMNO_OBLIGATORIO			NOT NULL,
  NOMBRE			VARCHAR2(40)	CONSTRAINT NOMBRE_ALUMNO_OBLIGATORIO			NOT NULL,
  LUGAR_NACIMIENTO		VARCHAR2(64)	CONSTRAINT LUGAR_NACIMIENTO_ALUMNO_OBLIGATORIO		NOT NULL,
  FECHA_NACIMIENTO		DATE		CONSTRAINT FECHA_NACIMIENTO_ALUMNO_OBLIGATORIO		NOT NULL,
  DOMICILIO			VARCHAR2(64)	CONSTRAINT DOMICILIO_ALUMNO_OBLIGATORIO			NOT NULL,
  TELEFONO			VARCHAR2(24)	CONSTRAINT TELEFONO_ALUMNO_OBLIGATORIO			NOT NULL,
  CORREO_ELECTRONICO		VARCHAR2(128)	CONSTRAINT CORREO_ELECTRONICO_ALUMNO_OBLIGATORIO	NOT NULL,
  COD_CIUDAD			NUMBER(12)	CONSTRAINT COD_CIUDAD_ALUMNO_OBLIGATORIO		NOT NULL,
  COD_PROVINCIA			NUMBER(9)	CONSTRAINT COD_PROVINCIA_ALUMNO_OBLIGATORIO		NOT NULL,
  COD_PAIS			NUMBER(6)	CONSTRAINT COD_PAIS_ALUMNO_OBLIGATORIO			NOT NULL,
  FECHA_INGRESO			DATE		CONSTRAINT FECHA_INGRESO_ALUMNO_OBLIGATORIO		NOT NULL,
  NRO_RESOLUCION_CS		VARCHAR2(6)	CONSTRAINT NRO_RESOLUCION_ALUMNO_OBLIGATORIO		NOT NULL);

CREATE TABLE MATERIAS
( COD_MATERIA			NUMBER(6),
  COD_CARRERA			NUMBER(3)	CONSTRAINT COD_CARRERA_MATERIA_OBLIGATORIO		NOT NULL,
  DESIGNACION_ACADEMICA		VARCHAR2(64)	CONSTRAINT DESIGNACION_ACADEMICA_MATERIA_OBLIGATORIO	NOT NULL,
  DURACION_ESTIMADA_MESES	NUMBER(2)	CONSTRAINT DURACION_ESTIMADA_MESES_MATERIA_OBLIGATORIO	NOT NULL,
  HORAS_SEMANALES		NUMBER(2)	CONSTRAINT HORAS_SEMANALES_MATERIA_OBLIGATORIO		NOT NULL,
  CARGA_HORARIA_TOTAL		NUMBER(3)	CONSTRAINT CARGA_HORARIA_TOTAL_MATERIA_OBLIGATORIO	NOT NULL,
  NRO_LEGAJO_PROFESOR		NUMBER(6)	CONSTRAINT NRO_LEGAJO_PROFESOR_MATERIA_OBLIGATORIO	NOT NULL);

CREATE TABLE COMISIONES
( COD_COMISION			NUMBER(6),
  COD_MATERIA			NUMBER(6)	CONSTRAINT COD_MATERIA_COMISION_OBLIGATORIO		NOT NULL,
  COD_CARRERA			NUMBER(3)	CONSTRAINT COD_CARRERA_COMISION_OBLIGATORIO		NOT NULL
  NRO_LEGAJO_PROFESOR		NUMBER(6)	CONSTRAINT NRO_LEGAJO_PROFESOR_COMISION_OBLIGATORIO	NOT NULL);

CREATE TABLE EXAMENES
( COD_EXAMEN			NUMBER(6),
  COD_CARRERA			NUMBER(3)	CONSTRAINT COD_CARRERA_EXAMEN_OBLIGATORIO		NOT NULL,
  COD_MATERIA			NUMBER(6)	CONSTRAINT COD_MATERIA_EXAMEN_OBLIGATORIO		NOT NULL,
  COD_COMISION			NUMBER(6)	CONSTRAINT COD_COMISION_EXAMEN_OBLIGATORIO		NOT NULL,
  NRO_LEGAJO_PROFESOR		NUMBER(6)	CONSTRAINT NRO_LEGAJO_PROFESOR_EXAMEN_OBLIGATORIO	NOT NULL,
  NRO_LEGAJO_ALUMNO		NUMBER(6)	CONSTRAINT NRO_LEGAJO_ALUMNO_EXAMEN_OBLIGATORIO		NOT NULL,
  FECHA				DATE		CONSTRAINT FECHA_EXAMEN_OBLIGATORIO			NOT NULL,
  NOTA				NUMBER(2)	CONSTRAINT NOTA_EXAMEN_OBLIGATORIO			NOT NULL);


ALTER TABLE ALUMNOS	ADD CONSTRAINT ALUMNOS_PK	PRIMARY KEY (NRO_LEGAJO_ALUMNO) ;
ALTER TABLE PROFESORES	ADD CONSTRAINT PROFESORES_PK	PRIMARY KEY (NRO_LEGAJO_PROFESOR);
ALTER TABLE PAISES	ADD CONSTRAINT PAISES_PK		PRIMARY KEY (COD_PAIS);
ALTER TABLE PROVINCIAS	ADD CONSTRAINT PROVINCIAS_PK	PRIMARY KEY (COD_PROVINCIA);
ALTER TABLE CIUDADES	ADD CONSTRAINT CIUDADES_PK	PRIMARY KEY (COD_CIUDAD);
ALTER TABLE CARRERAS	ADD CONSTRAINT CARRERAS_PK	PRIMARY KEY (COD_CARRERA);
ALTER TABLE MATERIAS	ADD CONSTRAINT MATERIAS_PK	PRIMARY KEY (COD_MATERIA);
ALTER TABLE COMISIONES	ADD CONSTRAINT COMISIONES_PK	PRIMARY KEY (COD_COMISION);
ALTER TABLE EXAMENES	ADD CONSTRAINT EXAMENES_PK	PRIMARY KEY (COD_EXAMEN);


ALTER TABLE ALUMNOS 	ADD CONSTRAINT ALUMNO_CARRERA	FOREING KEY (COD_CARRERA) REFERENCES CARRERAS (COD_CARRERA);
ALTER TABLE ALUMNOS 	ADD CONSTRAINT ALUMNO_CIUDAD	FOREING KEY (COD_CIUDAD) REFERENCES CIUDADES (COD_CIUDAD);
ALTER TABLE ALUMNOS 	ADD CONSTRAINT ALUMNO_PROVINCIA	FOREING KEY (COD_PROVINCIA) REFERENCES PROVINCIAS (COD_PROVINCIA);
ALTER TABLE ALUMNOS 	ADD CONSTRAINT ALUMNO_PAIS	FOREING KEY (COD_PAIS) REFERENCES PAISES (COD_PAIS);

ALTER TABLE PROFESORES 	ADD CONSTRAINT PROFESOR_CARRERA	FOREING KEY (COD_CARRERA) REFERENCES CARRERAS (COD_CARRERA);
ALTER TABLE PROFESORES 	ADD CONSTRAINT PROFESOR_CIUDAD	FOREING KEY (COD_CIUDAD) REFERENCES CIUDADES (COD_CIUDAD);
ALTER TABLE PROFESORES 	ADD CONSTRAINT PROFESOR_PROVINCIA FOREING KEY (COD_PROVINCIA) REFERENCES PROVINCIAS(COD_PROVINCIA);
ALTER TABLE PROFESORES 	ADD CONSTRAINT PROFESOR_PAIS	FOREING KEY (COD_PAIS) REFERENCES PAISES (COD_PAIS);

ALTER TABLE PROVINCIAS 	ADD CONSTRAINT PROVINCIA_PAIS	FOREING KEY (COD_PAIS) REFERENCES PAISES (COD_PAIS);

ALTER TABLE CIUDADES 	ADD CONSTRAINT CIUDAD_PAIS	FOREIGN KEY (COD_PAIS) REFERENCES PAISES (COD_PAIS);
ALTER TABLE CIUDADES 	ADD CONSTRAINT CIUDAD_PROVINCIA	FOREING KEY (COD_PROVINCIA) REFERENCES PROVINCIAS (COD_PROVINCIA);;

ALTER TABLE MATERIAS 	ADD CONSTRAINT MATERIA_CARRERA	FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS (COD_CARRERA);
ALTER TABLE MATERIAS 	ADD CONSTRAINT MATERIA_PROFESOR	FOREIGN KEY (NRO_LEGAJO_PROFESOR) REFERENCES PROFESORES (NRO_LEGAJO_PROFESOR);

ALTER TABLE COMISIONES 	ADD CONSTRAINT COMISION_MATERIA FOREIGN KEY (COD_MATERIA) REFERENCES MATERIAS (COD_MATERIA);
ALTER TABLE COMISIONES 	ADD CONSTRAINT COMISION_CARRERA FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS (COD_CARRERA);
ALTER TABLE COMISIONES 	ADD CONSTRAINT COMISION_PROFESOR FOREIGN KEY (NRO_LEGAJO_PROFESOR) REFERENCES PROFESORES (NRO_LEGAJO_PROFESOR);

ALTER TABLE EXAMENES ADD CONSTRAINT EXAMEN_CARRERA FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS (COD_CARRERA);
ALTER TABLE EXAMENES ADD CONSTRAINT EXAMEN_MATERIA FOREIGN KEY (COD_MATERIA) REFERENCES MATERIAS (COD_MATERIA);
ALTER TABLE EXAMENES ADD CONSTRAINT EXAMEN_COMISION FOREIGN KEY (COD_COMISION) REFERENCES COMISIONES (COD_COMISION);
ALTER TABLE EXAMENES ADD CONSTRAINT EXAMEN_PROFESOR FOREIGN KEY (NRO_LEGAJO_PROFESOR) REFERENCES PROFESORES (NRO_LEGAJO_PROFESOR);
ALTER TABLE EXAMENES ADD CONSTRAINT EXAMEN_ALUMNO FOREIGN KEY (NRO_LEGAJO_ALUMNO) REFERENCES ALUMNOS (NRO_LEGAJO_ALUMNO);


ALTER TABLE MATERIAS ADD CONSTRAINT NRO_LEGAJO_PROFESOR_MATERIAS_UNICO UNIQUE (NRO_LEGAJO_PROFESOR);

COMMIT;
